POST http://localhost:8080/estoque/cadastrar/produtos
Content-Type: application/json

{
    "nome":"Arroz",
    "categoria":"alimenticio",
    "descricao":"saco de arroz de 5Kg",
	  "quantidade":6, 
    "preco_unitario": 15.50
}